# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'org1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QComboBox, QCheckBox

selected_chapter = "Chapter 1"
selected_type = "填空"
selected_public = "Yes"
selection = ['0', '0', '0', '0']
answerA = ''
answerB = ''
answerC = ''
answerD = ''

def init_global():
    global selection
    global selected_public
    global selected_chapter
    global selected_public
    global selected_type
    global answerA
    global answerC
    global answerB
    global answerD
    selected_chapter = "Chapter 1"
    selected_type = "填空"
    selected_public = "Yes"
    selection = ['0', '0', '0', '0']
    answerA = ''
    answerB = ''
    answerC = ''
    answerD = ''

# 定义函数来修改全局变量
def modify_chapter(new):
    global selected_chapter
    selected_chapter = new


def modify_type(new):
    global selected_type
    selected_type = new


def modify_public(new):
    global selected_public
    selected_public = new


def modify_selection(i):
    global selection
    if selection[i] == '0':
        selection[i] = '1'
    else:
        selection[i] = '0'


def setA(s):
    global answerA
    answerA = s


def setB(s):
    global answerB
    answerB = s


def setC(s):
    global answerC
    answerC = s


def setD(s):
    global answerD
    answerD = s


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(934, 1052)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-130, 0, 4211, 61))
        self.label.setStyleSheet("color: rgb(255, 170, 0);\n"
                                 "background-color: rgb(255, 170, 0);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 75, 41))
        self.pushButton.setStyleSheet("background-color: rgb(255, 203, 151);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 10, 75, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 203, 151);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 10, 75, 41))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 203, 151);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 10, 75, 41))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 203, 151);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(380, 10, 75, 41))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 203, 151);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(780, 10, 75, 41))
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 203, 151);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 90, 941, 700))
        self.stackedWidget.setObjectName("stackedWidget")
        self.my_ad = QtWidgets.QWidget()
        self.my_ad.setObjectName("my_ad")
        self.wad = QtWidgets.QWidget(self.my_ad)
        self.wad.setGeometry(QtCore.QRect(30, 20, 861, 461))
        self.wad.setStyleSheet("border-radius:30px;\n"
                               "background-color: rgb(255, 203, 151);")
        self.wad.setObjectName("wad")
        self.nhello2 = QtWidgets.QLabel(self.wad)
        self.nhello2.setGeometry(QtCore.QRect(180, 40, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.nhello2.setFont(font)
        self.nhello2.setText("")
        self.nhello2.setObjectName("nhello2")
        self.ntp2 = QtWidgets.QLabel(self.wad)
        self.ntp2.setGeometry(QtCore.QRect(250, 120, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.ntp2.setFont(font)
        self.ntp2.setText("")
        self.ntp2.setObjectName("ntp2")
        self.cgb = QtWidgets.QPushButton(self.wad)
        self.cgb.setGeometry(QtCore.QRect(450, 180, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.cgb.setFont(font)
        self.cgb.setStyleSheet("background-color:rgb(254, 225, 64);")
        self.cgb.setObjectName("cgb")
        self.apb = QtWidgets.QPushButton(self.wad)
        self.apb.setGeometry(QtCore.QRect(450, 300, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.apb.setFont(font)
        self.apb.setStyleSheet("background-color:rgb(254, 225, 64);")
        self.apb.setObjectName("apb")
        self.tadmin = QtWidgets.QLabel(self.wad)
        self.tadmin.setGeometry(QtCore.QRect(120, 250, 291, 21))
        self.tadmin.setObjectName("tadmin")
        self.hello2 = QtWidgets.QLabel(self.wad)
        self.hello2.setGeometry(QtCore.QRect(80, 40, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.hello2.setFont(font)
        self.hello2.setObjectName("hello2")
        self.tp2 = QtWidgets.QLabel(self.wad)
        self.tp2.setGeometry(QtCore.QRect(80, 120, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.tp2.setFont(font)
        self.tp2.setObjectName("tp2")
        self.wgn = QtWidgets.QWidget(self.wad)
        self.wgn.setGeometry(QtCore.QRect(380, 100, 301, 181))
        self.wgn.setStyleSheet("#wgn{\n"
                               "   border-radius:30px;\n"
                               "   background-color:rgb(254, 225, 64);\n"
                               "}\n"
                               "\n"
                               "")
        self.wgn.setObjectName("wgn")
        self.groupname = QtWidgets.QLineEdit(self.wgn)
        self.groupname.setGeometry(QtCore.QRect(30, 60, 251, 41))
        self.groupname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupname.setText("")
        self.groupname.setObjectName("groupname")
        self.tgn = QtWidgets.QLabel(self.wgn)
        self.tgn.setGeometry(QtCore.QRect(100, 20, 151, 31))
        self.tgn.setStyleSheet("background-color:rgb(254, 225, 64);")
        self.tgn.setObjectName("tgn")
        self.wgn_cancel = QtWidgets.QPushButton(self.wgn)
        self.wgn_cancel.setGeometry(QtCore.QRect(60, 120, 41, 41))
        self.wgn_cancel.setStyleSheet("background-color: rgb(254, 225, 64)")
        self.wgn_cancel.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon/Cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wgn_cancel.setIcon(icon)
        self.wgn_cancel.setIconSize(QtCore.QSize(30, 30))
        self.wgn_cancel.setObjectName("wgn_cancel")
        self.wgn_ok = QtWidgets.QPushButton(self.wgn)
        self.wgn_ok.setGeometry(QtCore.QRect(210, 120, 41, 41))
        self.wgn_ok.setStyleSheet("background-color: rgb(254, 225, 64)")
        self.wgn_ok.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icon/Ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wgn_ok.setIcon(icon1)
        self.wgn_ok.setIconSize(QtCore.QSize(30, 30))
        self.wgn_ok.setObjectName("wgn_ok")
        self.waddp = QtWidgets.QWidget(self.wad)
        self.waddp.setGeometry(QtCore.QRect(380, 260, 301, 181))
        self.waddp.setStyleSheet("background-color: rgb(254, 225, 64);")
        self.waddp.setObjectName("waddp")
        self.waddpc = QtWidgets.QPushButton(self.waddp)
        self.waddpc.setGeometry(QtCore.QRect(260, 10, 41, 41))
        self.waddpc.setStyleSheet("background-color: rgb(254, 225, 64)")
        self.waddpc.setText("")
        self.waddpc.setIcon(icon)
        self.waddpc.setIconSize(QtCore.QSize(30, 30))
        self.waddpc.setObjectName("waddpc")
        self.waddpsearch = QtWidgets.QPushButton(self.waddp)
        self.waddpsearch.setGeometry(QtCore.QRect(230, 110, 41, 41))
        self.waddpsearch.setStyleSheet("background-color: rgb(255, 203, 151);\n"
                                       "border-radius:15px")
        self.waddpsearch.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icon/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.waddpsearch.setIcon(icon2)
        self.waddpsearch.setIconSize(QtCore.QSize(30, 30))
        self.waddpsearch.setObjectName("waddpsearch")

        self.personname = QtWidgets.QLineEdit(self.waddp)
        self.personname.setGeometry(QtCore.QRect(20, 110, 191, 41))
        self.personname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.personname.setText("")
        self.personname.setObjectName("personname")


        self.waddpcg = QtWidgets.QPushButton(self.waddp)
        self.waddpcg.setGeometry(QtCore.QRect(10, 30, 131, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.waddpcg.setFont(font)
        self.waddpcg.setStyleSheet("background-color: rgb(255, 203, 151);\n"
                                   "border-radius:15px")
        self.waddpcg.setObjectName("waddpcg")
        self.waddpgn = QtWidgets.QLabel(self.waddp)
        self.waddpgn.setGeometry(QtCore.QRect(160, 30, 91, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.waddpgn.setFont(font)
        self.waddpgn.setText("")
        self.waddpgn.setObjectName("waddpgn")
        self.stackedWidget.addWidget(self.my_ad)
        self.welcom = QtWidgets.QWidget()
        self.welcom.setObjectName("welcom")
        self.icwelc = QtWidgets.QLabel(self.welcom)
        self.icwelc.setGeometry(QtCore.QRect(40, 20, 201, 181))
        self.icwelc.setStyleSheet("background-image: url(:/images/icon/welcom.png);")
        self.icwelc.setText("")
        self.icwelc.setObjectName("icwelc")
        self.widget = QtWidgets.QWidget(self.welcom)
        self.widget.setGeometry(QtCore.QRect(260, 230, 631, 271))
        self.widget.setStyleSheet("background-color:rgb(255, 170, 0);\n"
                                  "border-bottom-left-radius:30px;\n"
                                  "border-bottom-right-radius:30px;\n"
                                  "\n"
                                  "")
        self.widget.setObjectName("widget")
        self.abus = QtWidgets.QLabel(self.widget)
        self.abus.setGeometry(QtCore.QRect(250, -10, 291, 111))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.abus.setFont(font)
        self.abus.setObjectName("abus")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setGeometry(QtCore.QRect(130, 70, 421, 311))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.widget_2 = QtWidgets.QWidget(self.welcom)
        self.widget_2.setGeometry(QtCore.QRect(260, 50, 631, 181))
        self.widget_2.setStyleSheet("background-color:rgb(254, 225, 64);\n"
                                    "border-top-left-radius:30px;\n"
                                    "border-top-right-radius:30px;\n"
                                    "\n"
                                    "")
        self.widget_2.setObjectName("widget_2")
        self.abus_2 = QtWidgets.QLabel(self.widget_2)
        self.abus_2.setGeometry(QtCore.QRect(30, 10, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.abus_2.setFont(font)
        self.abus_2.setObjectName("abus_2")
        self.abus_3 = QtWidgets.QLabel(self.widget_2)
        self.abus_3.setGeometry(QtCore.QRect(40, 70, 551, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.abus_3.setFont(font)
        self.abus_3.setObjectName("abus_3")
        self.stackedWidget.addWidget(self.welcom)
        self.upload = QtWidgets.QWidget()
        self.upload.setObjectName("upload")
        self.title_2 = QtWidgets.QLabel(self.upload)
        self.title_2.setGeometry(QtCore.QRect(40, 30, 41, 16))
        self.title_2.setObjectName("title_2")

        self.lineEdit_name = QtWidgets.QLineEdit(self.upload)
        self.lineEdit_name.setGeometry(QtCore.QRect(90, 30, 781, 20))
        self.lineEdit_name.setObjectName("lineEdit_name")

        self.title = QtWidgets.QLabel(self.upload)
        self.title.setGeometry(QtCore.QRect(30, 80, 54, 12))
        self.title.setObjectName("title")

        self.textEdit_title = QtWidgets.QTextEdit(self.upload)
        self.textEdit_title.setGeometry(QtCore.QRect(90, 70, 781, 181))
        self.textEdit_title.setObjectName("textEdit_title")

        self.chapter = QtWidgets.QLabel(self.upload)
        self.chapter.setGeometry(QtCore.QRect(40, 280, 121, 30))
        self.chapter.setObjectName("chapter")

        # self.lineEdit_public = QtWidgets.QLineEdit(self.upload)
        # self.lineEdit_public.setGeometry(QtCore.QRect(180, 280, 651, 20))
        # self.lineEdit_public.setObjectName("lineEdit_public")

        self.lineEdit_public = QComboBox(self.upload)
        self.lineEdit_public.setGeometry(QtCore.QRect(110, 280, 120, 30))
        self.lineEdit_public.addItem("Yes")
        self.lineEdit_public.addItem("No")
        self.lineEdit_public.setObjectName("lineEdit_public")

        def Modify_public():
            modify_public(self.lineEdit_public.currentText())
            print("Selected value:", self.lineEdit_public.currentText())

        # 将槽函数与下拉框的选择变化信号关联起来
        self.lineEdit_public.currentIndexChanged.connect(Modify_public)

        self.my_type = QtWidgets.QLabel(self.upload)
        self.my_type.setGeometry(QtCore.QRect(40, 320, 121, 40))
        self.my_type.setObjectName("my_type")

        # self.lineEdit_type = QtWidgets.QLineEdit(self.upload)
        # self.lineEdit_type.setGeometry(QtCore.QRect(180, 330, 711, 20))
        # self.lineEdit_type.setObjectName("lineEdit_type")

        self.lineEdit_type = QComboBox(self.upload)
        self.lineEdit_type.setGeometry(QtCore.QRect(110, 330, 120, 30))
        self.lineEdit_type.addItem("填空")
        self.lineEdit_type.addItem("选择")
        self.lineEdit_type.setObjectName("lineEdit_type")

        def create_answer():
            if selected_type == "选择":
                self.lineEdit_answer.deleteLater()

                # self.lineEdit_answerall = QtWidgets.QLineEdit(self.upload)
                # self.lineEdit_answerall.setGeometry(QtCore.QRect(110, 380, 771, 20))
                # self.lineEdit_answerall.setObjectName("lineEdit_answerall")
                # self.lineEdit_answerall.setVisible(True)
                self.A = QCheckBox(self.upload)
                self.A.setGeometry(QtCore.QRect(60, 400, 90, 20))
                self.A.setObjectName('A')
                self.A.setVisible(True)

                self.B = QCheckBox(self.upload)
                self.B.setGeometry(QtCore.QRect(60, 430, 90, 20))
                self.B.setObjectName('B')
                self.B.setVisible(True)

                self.C = QCheckBox(self.upload)
                self.C.setGeometry(QtCore.QRect(60, 460, 90, 20))
                self.C.setObjectName('C')
                self.C.setVisible(True)

                self.D = QCheckBox(self.upload)
                self.D.setGeometry(QtCore.QRect(60, 490, 90, 20))
                self.D.setObjectName('D')
                self.D.setVisible(True)

                self.lineEdit_answerA = QtWidgets.QLineEdit(self.upload)
                self.lineEdit_answerA.setGeometry(QtCore.QRect(110, 400, 771, 20))
                self.lineEdit_answerA.setObjectName("lineEdit_answerA")
                self.lineEdit_answerA.setVisible(True)

                self.lineEdit_answerB = QtWidgets.QLineEdit(self.upload)
                self.lineEdit_answerB.setGeometry(QtCore.QRect(110, 430, 771, 20))
                self.lineEdit_answerB.setObjectName("lineEdit_answerB")
                self.lineEdit_answerB.setVisible(True)

                self.lineEdit_answerC = QtWidgets.QLineEdit(self.upload)
                self.lineEdit_answerC.setGeometry(QtCore.QRect(110, 460, 771, 20))
                self.lineEdit_answerC.setObjectName("lineEdit_answerC")
                self.lineEdit_answerC.setVisible(True)

                self.lineEdit_answerD = QtWidgets.QLineEdit(self.upload)
                self.lineEdit_answerD.setGeometry(QtCore.QRect(110, 490, 771, 20))
                self.lineEdit_answerD.setObjectName("lineEdit_answerD")
                self.lineEdit_answerD.setVisible(True)

                self.A.stateChanged.connect(handleCheckboxA)
                self.B.stateChanged.connect(handleCheckboxB)
                self.C.stateChanged.connect(handleCheckboxC)
                self.D.stateChanged.connect(handleCheckboxD)

                self.lineEdit_answerA.textChanged.connect(TextA)
                self.lineEdit_answerB.textChanged.connect(TextB)
                self.lineEdit_answerC.textChanged.connect(TextC)
                self.lineEdit_answerD.textChanged.connect(TextD)


                self.answer_2.setGeometry(QtCore.QRect(40, 535, 70, 40))
                self.lineEdit_chapter.setGeometry(QtCore.QRect(110, 540, 120, 30))

            else:
                self.answer_2.setGeometry(QtCore.QRect(40, 425, 70, 40))
                self.lineEdit_chapter.setGeometry(QtCore.QRect(110, 430, 120, 30))

                self.lineEdit_answerA.deleteLater()
                self.lineEdit_answerB.deleteLater()
                self.lineEdit_answerC.deleteLater()
                self.lineEdit_answerD.deleteLater()
                self.A.deleteLater()
                self.B.deleteLater()
                self.C.deleteLater()
                self.D.deleteLater()

                self.lineEdit_answer = QtWidgets.QLineEdit(self.upload)
                self.lineEdit_answer.setGeometry(QtCore.QRect(110, 380, 771, 20))
                self.lineEdit_answer.setObjectName("lineEdit_answer")
                self.lineEdit_answer.setVisible(True)

        self.lineEdit_answer = QtWidgets.QLineEdit(self.upload)
        self.lineEdit_answer.setGeometry(QtCore.QRect(110, 380, 771, 20))
        self.lineEdit_answer.setObjectName("lineEdit_answer")

        def handleCheckboxA():
            modify_selection(0)

        def handleCheckboxB():
            modify_selection(1)

        def handleCheckboxC():
            modify_selection(2)

        def handleCheckboxD():
            modify_selection(3)
        def TextA(text):
            print(text)
            setA(text)

        def TextB(text):
            setB(text)

        def TextC(text):
            setC(text)

        def TextD(text):
            setD(text)

        def Modify_type():
            modify_type(self.lineEdit_type.currentText())
            print("Selected value:", selected_type)
            create_answer()

        # 将槽函数与下拉框的选择变化信号关联起来
        self.lineEdit_type.currentIndexChanged.connect(Modify_type)

        self.answer = QtWidgets.QLabel(self.upload)
        self.answer.setGeometry(QtCore.QRect(40, 380, 54, 12))
        self.answer.setObjectName("answer")

        # self.lineEdit_answer = QtWidgets.QLineEdit(self.upload)
        # self.lineEdit_answer.setGeometry(QtCore.QRect(110, 380, 771, 20))
        # self.lineEdit_answer.setObjectName("lineEdit_answer")

        self.answer_2 = QtWidgets.QLabel(self.upload)
        self.answer_2.setGeometry(QtCore.QRect(40, 425, 70, 40))
        self.answer_2.setObjectName("answer_2")

        # self.lineEdit_chapter = QtWidgets.QLineEdit(self.upload)
        # self.lineEdit_chapter.setGeometry(QtCore.QRect(110, 430, 771, 20))
        # self.lineEdit_chapter.setObjectName("lineEdit_chapter")

        self.lineEdit_chapter = QComboBox(self.upload)
        self.lineEdit_chapter.setGeometry(QtCore.QRect(110, 430, 120, 30))
        # 添加选项
        self.lineEdit_chapter.addItem("Chapter 1")
        self.lineEdit_chapter.addItem("Chapter 2")
        self.lineEdit_chapter.addItem("Chapter 3")
        self.lineEdit_chapter.addItem("Chapter 4")
        self.lineEdit_chapter.addItem("Chapter 5")
        self.lineEdit_chapter.addItem("Chapter 6")
        self.lineEdit_chapter.addItem("Chapter 7")
        self.lineEdit_chapter.setObjectName("lineEdit_chapter")

        def Modify_chapter():
            modify_chapter(self.lineEdit_chapter.currentText())
            print("Selected value:", self.lineEdit_chapter.currentText())

        # 将槽函数与下拉框的选择变化信号关联起来
        self.lineEdit_chapter.currentIndexChanged.connect(Modify_chapter)

        self.pushButton_7 = QtWidgets.QPushButton(self.upload)
        self.pushButton_7.setGeometry(QtCore.QRect(780, 470, 75, 41))
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 203, 151);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.stackedWidget.addWidget(self.upload)
        self.search = QtWidgets.QWidget()
        self.search.setObjectName("search")
        self.fsearch = QtWidgets.QFrame(self.search)
        self.fsearch.setGeometry(QtCore.QRect(-10, -20, 921, 531))
        self.fsearch.setStyleSheet("")
        self.fsearch.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fsearch.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fsearch.setObjectName("fsearch")
        self.fsearch_2 = QtWidgets.QFrame(self.fsearch)
        self.fsearch_2.setGeometry(QtCore.QRect(20, 30, 921, 531))
        self.fsearch_2.setStyleSheet("")
        self.fsearch_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fsearch_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fsearch_2.setObjectName("fsearch_2")

        self.pushButton_9 = QtWidgets.QPushButton(self.fsearch_2)
        self.pushButton_9.setGeometry(QtCore.QRect(90, 40, 261, 131))
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 203, 151);\n"
"font: 24pt \"Agency FB\";\n"
"font: 22pt \"Agency FB\";")

        self.search_group_name = QtWidgets.QLineEdit(self.fsearch_2)
        self.search_group_name.setGeometry(QtCore.QRect(400, 80, 400, 40))
        self.search_group_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.search_group_name.setText("")
        self.search_group_name.setObjectName("search_group_name")

        self.searchicon = QtWidgets.QPushButton(self.fsearch_2)
        self.searchicon.setGeometry(QtCore.QRect(820, 80, 41, 40))
        self.searchicon.setStyleSheet("background-color: rgb(255, 203, 151);\n"
                                       "border-radius:15px")
        self.searchicon.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icon/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchicon.setIcon(icon2)
        self.searchicon.setIconSize(QtCore.QSize(30, 30))
        self.searchicon.setObjectName("searchicon")

        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.fsearch_2)
        self.pushButton_10.setGeometry(QtCore.QRect(90, 260, 261, 131))
        self.pushButton_10.setStyleSheet("background-color: rgb(255, 203, 151);\n"
"font: 26pt \"Agency FB\";\n"
"font: 24pt \"Agency FB\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_type = QtWidgets.QLabel(self.fsearch_2)
        self.label_type.setGeometry(QtCore.QRect(100, 80, 61, 41))
        self.label_type.setStyleSheet("font: 18pt \"Agency FB\";")
        self.label_type.setObjectName("label_type")
        self.label_chapter = QtWidgets.QLabel(self.fsearch_2)
        self.label_chapter.setGeometry(QtCore.QRect(100, 160, 61, 41))
        self.label_chapter.setStyleSheet("font: 18pt \"Agency FB\";")
        self.label_chapter.setObjectName("label_chapter")
        self.lineEdit_type_2 = QtWidgets.QLineEdit(self.fsearch_2)
        self.lineEdit_type_2.setGeometry(QtCore.QRect(190, 80, 291, 31))
        self.lineEdit_type_2.setStyleSheet("font: 14pt \"Agency FB\";")
        self.lineEdit_type_2.setObjectName("lineEdit_type_2")
        self.lineEdit_chapter_2 = QtWidgets.QLineEdit(self.fsearch_2)
        self.lineEdit_chapter_2.setGeometry(QtCore.QRect(190, 160, 291, 31))
        self.lineEdit_chapter_2.setStyleSheet("font: 14pt \"Agency FB\";")
        self.lineEdit_chapter_2.setObjectName("lineEdit_chapter_2")
        self.pushButton_11 = QtWidgets.QPushButton(self.fsearch_2)
        self.pushButton_11.setGeometry(QtCore.QRect(760, 430, 91, 41))
        self.pushButton_11.setStyleSheet("background-color: rgb(255, 203, 151);\n"
"font: 12pt \"Agency FB\";\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")

        self.widget_btn = QtWidgets.QWidget(self.fsearch_2)
        self.widget_btn.setGeometry(QtCore.QRect(0, 0, 811, 521))
        self.widget_btn.setObjectName("widget_btn")



        self.button0 = QtWidgets.QPushButton(self.widget_btn)
        self.button0.setGeometry(QtCore.QRect(60, 0, 731, 51))
        self.button0.setStyleSheet("font: 14pt \"Agency FB\";")
        self.button0.setObjectName("button0")
        self.button1 = QtWidgets.QPushButton(self.widget_btn)
        self.button1.setGeometry(QtCore.QRect(60, 60, 731, 51))
        self.button1.setStyleSheet("font: 14pt \"Agency FB\";")
        self.button1.setObjectName("button1")
        self.button2 = QtWidgets.QPushButton(self.widget_btn)
        self.button2.setGeometry(QtCore.QRect(60, 120, 731, 51))
        self.button2.setStyleSheet("font: 14pt \"Agency FB\";")
        self.button2.setObjectName("button2")
        self.label_key = QtWidgets.QLabel(self.fsearch_2)
        self.label_key.setGeometry(QtCore.QRect(70, 10, 91, 41))
        self.label_key.setStyleSheet("font: 18pt \"Agency FB\";")
        self.label_key.setObjectName("label_key")
        self.lineEdit_key = QtWidgets.QLineEdit(self.fsearch_2)
        self.lineEdit_key.setGeometry(QtCore.QRect(190, 20, 291, 31))
        self.lineEdit_key.setStyleSheet("font: 14pt \"Agency FB\";")
        self.lineEdit_key.setObjectName("lineEdit_key")
        self.pushButton_12 = QtWidgets.QPushButton(self.fsearch_2)
        self.pushButton_12.setGeometry(QtCore.QRect(390, 210, 91, 41))
        self.pushButton_12.setStyleSheet("background-color: rgb(255, 203, 151);\n"
"font: 12pt \"Agency FB\";\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.widget_ques = QtWidgets.QWidget(self.fsearch_2)
        self.widget_ques.setGeometry(QtCore.QRect(0, -60, 841, 541))
        self.widget_ques.setStyleSheet("")
        self.widget_ques.setObjectName("widget_ques")
        self.question0 = QtWidgets.QPushButton(self.widget_ques)
        self.question0.setGeometry(QtCore.QRect(50, 42, 781, 91))
        self.question0.setObjectName("question0")
        self.question1 = QtWidgets.QPushButton(self.widget_ques)
        self.question1.setGeometry(QtCore.QRect(50, 150, 781, 91))
        self.question1.setObjectName("question1")
        self.question2 = QtWidgets.QPushButton(self.widget_ques)
        self.question2.setGeometry(QtCore.QRect(50, 260, 781, 91))
        self.question2.setObjectName("question2")
        self.question3 = QtWidgets.QPushButton(self.widget_ques)
        self.question3.setGeometry(QtCore.QRect(50, 370, 781, 91))
        self.question3.setObjectName("question3")
        self.widget_ques.raise_()
        self.widget_btn.raise_()
        self.pushButton_9.raise_()
        self.pushButton_10.raise_()
        self.label_type.raise_()
        self.label_chapter.raise_()
        self.lineEdit_type_2.raise_()
        self.lineEdit_chapter_2.raise_()
        self.pushButton_11.raise_()
        self.label_key.raise_()
        self.lineEdit_key.raise_()
        self.pushButton_12.raise_()
        self.stackedWidget.addWidget(self.search)
        self.my_norm = QtWidgets.QWidget()
        self.my_norm.setObjectName("my_norm")
        self.wnorm = QtWidgets.QWidget(self.my_norm)
        self.wnorm.setGeometry(QtCore.QRect(40, 20, 861, 461))
        self.wnorm.setStyleSheet("border-radius:30px;\n"
"background-color: rgb(255, 203, 151);")
        self.wnorm.setObjectName("wnorm")
        self.hello1 = QtWidgets.QLabel(self.wnorm)
        self.hello1.setGeometry(QtCore.QRect(130, 20, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.hello1.setFont(font)
        self.hello1.setObjectName("hello1")
        self.tp1 = QtWidgets.QLabel(self.wnorm)
        self.tp1.setGeometry(QtCore.QRect(130, 60, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.tp1.setFont(font)
        self.tp1.setObjectName("tp1")
        self.atg = QtWidgets.QPushButton(self.wnorm)
        self.atg.setGeometry(QtCore.QRect(680, 30, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.atg.setFont(font)
        self.atg.setStyleSheet("background-color:rgb(255, 170, 0)")
        self.atg.setObjectName("atg")
        self.tg = QtWidgets.QLabel(self.wnorm)
        self.tg.setGeometry(QtCore.QRect(330, 140, 181, 21))
        self.tg.setObjectName("tg")
        self.bg = QtWidgets.QLabel(self.wnorm)
        self.bg.setGeometry(QtCore.QRect(70, 180, 741, 181))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bg.setFont(font)
        self.bg.setStyleSheet("border:1px solid #696969;\n"
"")
        self.bg.setObjectName("bg")
        self.nhello1 = QtWidgets.QLabel(self.wnorm)
        self.nhello1.setGeometry(QtCore.QRect(230, 20, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.nhello1.setFont(font)
        self.nhello1.setText("")
        self.nhello1.setObjectName("nhello1")
        self.ntp1 = QtWidgets.QLabel(self.wnorm)
        self.ntp1.setGeometry(QtCore.QRect(290, 60, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.ntp1.setFont(font)
        self.ntp1.setText("")
        self.ntp1.setObjectName("ntp1")
        self.stackedWidget.addWidget(self.my_norm)
        self.problems = QtWidgets.QWidget()
        self.problems.setObjectName("problems")
        self.label_2 = QtWidgets.QLabel(self.problems)
        self.label_2.setGeometry(QtCore.QRect(130, 150, 591, 211))
        self.label_2.setObjectName("label_2")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.problems)
        self.stackedWidget_2.setGeometry(QtCore.QRect(10, 0, 811, 381))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton_28 = QtWidgets.QPushButton(self.page)
        self.pushButton_28.setGeometry(QtCore.QRect(250, 0, 93, 28))
        self.pushButton_28.setObjectName("pushButton_28")
        self.layoutWidget = QtWidgets.QWidget(self.page)
        self.layoutWidget.setGeometry(QtCore.QRect(600, 330, 195, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_29 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_29.setObjectName("pushButton_29")
        self.horizontalLayout.addWidget(self.pushButton_29)
        self.pushButton_30 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout.addWidget(self.pushButton_30)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.page)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 30, 351, 291))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.page)
        self.layoutWidget_2.setGeometry(QtCore.QRect(410, 30, 231, 281))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.A = QtWidgets.QPushButton(self.layoutWidget_2)
        self.A.setObjectName("A")
        self.verticalLayout.addWidget(self.A)
        self.B = QtWidgets.QPushButton(self.layoutWidget_2)
        self.B.setObjectName("B")
        self.verticalLayout.addWidget(self.B)
        self.C = QtWidgets.QPushButton(self.layoutWidget_2)
        self.C.setObjectName("C")
        self.verticalLayout.addWidget(self.C)
        self.D = QtWidgets.QPushButton(self.layoutWidget_2)
        self.D.setObjectName("D")
        self.verticalLayout.addWidget(self.D)
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 171, 16))
        self.label_4.setObjectName("label_4")
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.pushButton_35 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_35.setGeometry(QtCore.QRect(270, 10, 93, 28))
        self.pushButton_35.setObjectName("pushButton_35")
        self.layoutWidget_3 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(620, 340, 195, 30))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_36 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_36.setObjectName("pushButton_36")
        self.horizontalLayout_2.addWidget(self.pushButton_36)
        self.pushButton_37 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_37.setObjectName("pushButton_37")
        self.horizontalLayout_2.addWidget(self.pushButton_37)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.page_2)
        self.textBrowser_3.setGeometry(QtCore.QRect(20, 40, 351, 291))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.layoutWidget_4 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(430, 40, 231, 281))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.answer1 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.answer1.setObjectName("answer1")
        self.verticalLayout_2.addWidget(self.answer1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 72, 15))
        self.label_5.setObjectName("label_5")
        self.submit = QtWidgets.QPushButton(self.page_2)
        self.submit.setGeometry(QtCore.QRect(680, 260, 93, 23))
        self.submit.setObjectName("submit")
        self.stackedWidget_2.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.pushButton_38 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_38.setGeometry(QtCore.QRect(250, 0, 93, 28))
        self.pushButton_38.setObjectName("pushButton_38")
        self.layoutWidget_5 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget_5.setGeometry(QtCore.QRect(600, 330, 195, 30))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_39 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pushButton_39.setObjectName("pushButton_39")
        self.horizontalLayout_3.addWidget(self.pushButton_39)
        self.pushButton_40 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pushButton_40.setObjectName("pushButton_40")
        self.horizontalLayout_3.addWidget(self.pushButton_40)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.page_3)
        self.textBrowser_4.setGeometry(QtCore.QRect(0, 30, 351, 291))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.layoutWidget_6 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget_6.setGeometry(QtCore.QRect(410, 30, 231, 281))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_3.addWidget(self.checkBox_4)
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_3.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_3.addWidget(self.checkBox_3)
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(0, 10, 72, 15))
        self.label_6.setObjectName("label_6")
        self.stackedWidget_2.addWidget(self.page_3)
        self.stackedWidget.addWidget(self.problems)
        self.log = QtWidgets.QWidget()
        self.log.setObjectName("log")
        self.label_3 = QtWidgets.QLabel(self.log)
        self.label_3.setGeometry(QtCore.QRect(160, 130, 261, 61))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.log)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(5)
        self.stackedWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "上传问题"))
        self.pushButton_2.setText(_translate("MainWindow", "搜索"))
        self.pushButton_3.setText(_translate("MainWindow", "查看问题"))
        self.pushButton_4.setText(_translate("MainWindow", "错误日志"))
        self.pushButton_5.setText(_translate("MainWindow", "我的"))
        self.pushButton_6.setText(_translate("MainWindow", "关于"))
        self.cgb.setText(_translate("MainWindow", "创建组"))
        self.apb.setText(_translate("MainWindow", "添加用户"))
        self.tadmin.setText(_translate("MainWindow", "尊敬的管理员，你可以执行的操作有"))
        self.hello2.setText(_translate("MainWindow", "Hello"))
        self.tp2.setText(_translate("MainWindow", "你的身份是："))
        self.groupname.setPlaceholderText(_translate("MainWindow", "group name here"))
        self.tgn.setText(_translate("MainWindow", "请输入组名"))
        self.personname.setPlaceholderText(_translate("MainWindow", "person name is "))
        self.waddpcg.setText(_translate("MainWindow", "选择一个组："))
        self.abus.setText(_translate("MainWindow", "关于我们"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">项目名称：pyExercise</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">参与人员：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">   段宇函</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">   方沐阳</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">   陆莹锦</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">   王芊文</span></p></body></html>"))
        self.abus_2.setText(_translate("MainWindow", "欢迎来到pyExercise"))
        self.abus_3.setText(_translate("MainWindow", "这里是一个帮助你掌握题目、获得成长的python小程序"))
        self.title_2.setText(_translate("MainWindow", "name"))
        self.title.setText(_translate("MainWindow", "title"))
        self.chapter.setText(_translate("MainWindow", "public： yes/no"))
        self.my_type.setText(_translate("MainWindow", "type： 填空/选择"))
        self.answer.setText(_translate("MainWindow", "answer"))
        self.answer_2.setText(_translate("MainWindow", "chapter"))
        self.pushButton_7.setText(_translate("MainWindow", "上传"))
        self.pushButton_9.setText(_translate("MainWindow", "搜索组"))
        self.pushButton_10.setText(_translate("MainWindow", "搜索问题"))
        self.label_type.setText(_translate("MainWindow", "类型"))
        self.label_chapter.setText(_translate("MainWindow", "章节"))
        self.pushButton_11.setText(_translate("MainWindow", "下一页"))
        self.button0.setText(_translate("MainWindow", "PushButton"))
        self.button1.setText(_translate("MainWindow", "PushButton"))
        self.button2.setText(_translate("MainWindow", "PushButton"))
        self.label_key.setText(_translate("MainWindow", "关键字"))
        self.pushButton_12.setText(_translate("MainWindow", "搜索"))
        self.question0.setText(_translate("MainWindow", "PushButton"))
        self.question1.setText(_translate("MainWindow", "PushButton"))
        self.question2.setText(_translate("MainWindow", "PushButton"))
        self.question3.setText(_translate("MainWindow", "PushButton"))
        self.hello1.setText(_translate("MainWindow", "Hello"))
        self.tp1.setText(_translate("MainWindow", "你的身份是："))
        self.atg.setText(_translate("MainWindow", "加入组"))
        self.tg.setText(_translate("MainWindow", "以下是你目前加入的组"))
        self.bg.setText(_translate("MainWindow", "you are not in any group"))
        self.label_2.setText(_translate("MainWindow", "查看问题"))
        self.pushButton_28.setText(_translate("MainWindow", "收藏"))
        self.pushButton_29.setText(_translate("MainWindow", "上一题"))
        self.pushButton_30.setText(_translate("MainWindow", "下一题"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">题目</p></body></html>"))
        self.A.setText(_translate("MainWindow", "A"))
        self.B.setText(_translate("MainWindow", "B"))
        self.C.setText(_translate("MainWindow", "C"))
        self.D.setText(_translate("MainWindow", "D"))
        self.label_4.setText(_translate("MainWindow", "选择题"))
        self.pushButton_35.setText(_translate("MainWindow", "收藏"))
        self.pushButton_36.setText(_translate("MainWindow", "上一题"))
        self.pushButton_37.setText(_translate("MainWindow", "下一题"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">题目</p></body></html>"))
        self.answer1.setPlaceholderText(_translate("MainWindow", "空1"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "空2"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "空3"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "空4"))
        self.label_5.setText(_translate("MainWindow", "填空题"))
        self.submit.setText(_translate("MainWindow", "提交"))
        self.pushButton_38.setText(_translate("MainWindow", "收藏"))
        self.pushButton_39.setText(_translate("MainWindow", "上一题"))
        self.pushButton_40.setText(_translate("MainWindow", "下一题"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">题目</p></body></html>"))
        self.checkBox_4.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_2.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_3.setText(_translate("MainWindow", "CheckBox"))
        self.label_6.setText(_translate("MainWindow", "多选题"))
        self.label_3.setText(_translate("MainWindow", "错误日志"))
