# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Org\org1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-60, 0, 4211, 61))
        self.label.setStyleSheet("color: rgb(255, 170, 0);\n"
"background-color: rgb(255, 170, 0);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 75, 41))
        self.pushButton.setStyleSheet("background-color: rgb(255, 203, 151);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 10, 75, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 203, 151);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 10, 75, 41))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 203, 151);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 10, 75, 41))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 203, 151);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(380, 10, 75, 41))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 203, 151);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(470, 10, 75, 41))
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 203, 151);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(680, 520, 75, 41))
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 203, 151);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(40, 80, 75, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(43, 113, 851, 391))
        self.textEdit.setObjectName("textEdit")
        self.search = QtWidgets.QFrame(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(10, 70, 921, 531))
        self.search.setStyleSheet("")
        self.search.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search.setObjectName("search")
        self.lineEdit = QtWidgets.QLineEdit(self.search)
        self.lineEdit.setGeometry(QtCore.QRect(30, 29, 871, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_9 = QtWidgets.QPushButton(self.search)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 80, 71, 31))
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 203, 151);")
        self.pushButton_9.setObjectName("pushButton_9")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "上传问题"))
        self.pushButton_2.setText(_translate("MainWindow", "搜索"))
        self.pushButton_3.setText(_translate("MainWindow", "查看问题"))
        self.pushButton_4.setText(_translate("MainWindow", "错误日志"))
        self.pushButton_5.setText(_translate("MainWindow", "我的"))
        self.pushButton_6.setText(_translate("MainWindow", "关于"))
        self.pushButton_7.setText(_translate("MainWindow", "上传"))
        self.pushButton_8.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_9.setText(_translate("MainWindow", "搜索"))
